import { StyleSheet } from "react-native";

// Shared UI baseline for any "asset detail" screen.
// The FII detail screen is the reference, and other asset classes should follow it.
export const assetDetailStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#fff" },
  container: { flexGrow: 1, padding: 16, backgroundColor: "#fff" },
  headerRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  ticker: { fontSize: 26, fontWeight: "800" },
  starBtn: { padding: 6, marginRight: -4 },
  star: { fontSize: 22, color: "#999" },
  starActive: { color: "#f2b400" },
  price: { fontSize: 18, marginTop: 6 },
  metaBox: {
    marginTop: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#e6e6e6",
    backgroundColor: "#fafafa",
    gap: 4,
  },
  metaLine: { fontSize: 12, color: "#555" },
  status: { fontSize: 16, fontWeight: "700", marginTop: 14 },
  message: { fontSize: 14, marginTop: 6, marginBottom: 12 },
  scoreCard: {
    borderWidth: 1,
    borderColor: "#dbeafe",
    backgroundColor: "#f0f7ff",
    borderRadius: 12,
    padding: 12,
    gap: 6,
  },
  scoreTitle: { fontSize: 14, fontWeight: "800", color: "#1d4ed8" },
  scoreLabel: { fontSize: 12, fontWeight: "700", color: "#1f2937" },
  scoreReason: { fontSize: 12, color: "#374151" },
  block: { gap: 8, marginTop: 16 },
  sectionTitle: { fontSize: 16, fontWeight: "700", marginBottom: 4 },
  kpi: { fontSize: 14, color: "#111" },
  kpiMuted: { fontSize: 14, color: "#777" },
  paragraph: { fontSize: 13, color: "#333", lineHeight: 18 },
  helper: { fontSize: 12, color: "#666" },
  inlineRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  weeklySummary: { fontSize: 12, color: "#444", marginTop: 6 },
  simHint: { fontSize: 12, color: "#555" },
  input: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 10,
    backgroundColor: "#fff",
  },
  alertActions: { flexDirection: "row", gap: 8 },
  alertPrimary: {
    flex: 1,
    borderRadius: 10,
    backgroundColor: "#111827",
    alignItems: "center",
    paddingVertical: 10,
  },
  alertPrimaryText: { color: "#fff", fontWeight: "700", fontSize: 12 },
  alertSecondary: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#b91c1c",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  alertSecondaryText: { color: "#b91c1c", fontWeight: "700", fontSize: 12 },
  switchRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  switchLabel: { fontSize: 13, color: "#333", flex: 1, paddingRight: 8 },
  rateInfo: { fontSize: 12, color: "#555" },
  resultGroup: { gap: 10 },
  simSummary: { fontSize: 13, color: "#333", fontWeight: "700" },
  resultBox: {
    borderWidth: 1,
    borderColor: "#d9e8ff",
    backgroundColor: "#f3f8ff",
    borderRadius: 10,
    padding: 10,
    gap: 6,
  },
  resultBoxAlt: {
    borderWidth: 1,
    borderColor: "#e3e3e3",
    backgroundColor: "#fafafa",
    borderRadius: 10,
    padding: 10,
    gap: 6,
  },
  resultTitle: { fontSize: 13, fontWeight: "700", color: "#111" },
  resultLine: { fontSize: 13, color: "#111" },
  simDisclaimer: { fontSize: 12, color: "#666" },
  eventsTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  eventsLinkBtn: {
    backgroundColor: "#0f172a",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  eventsLinkText: { color: "#fff", fontWeight: "800", fontSize: 12 },
  eventRow: {
    borderWidth: 1,
    borderColor: "#e2e8f0",
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 10,
    gap: 4,
  },
  eventTitle: { fontSize: 12, fontWeight: "800", color: "#0f172a" },
  eventSubject: { fontSize: 12, color: "#334155" },
  eventMeta: { fontSize: 11, color: "#64748b" },
  disclaimer: { marginTop: 24, fontSize: 12, color: "#666" },
});
